# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
# 
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: rappdw/docker-java-python
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/example-pip-circle

    steps:
      - checkout
      - run: 
          name: install dependencies
          command: |
            python setup.py install
            python3 -m venv venv
            . venv/bin/activate
            --user ${530faa44-3804-4a12-98e9-9652075d1453}
            https://scripts.scantist.com/ci-travis.sh
